version: 2
jobs:
  build:
    working_directory: ~/hangeul4s

    docker:
      - image: circleci/openjdk:8-jdk

#    environment:
#      # Customize the JVM maximum heap limit
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Clean and compile project for all supported Scala versions
          command: cat /dev/null | sbt +test:clean +test:compile

      # Cache dependencies for next build
      - save_cache:
          key: v1-dependencies--{{ checksum "build.sbt" }}
          paths:
            - ~/.ivy2/cache
            - ~/.m2
            - ~/.sbt

      - run:
          name: Run tests for all supported Scala versions and produce coverage report
          command: cat /dev/null | sbt coverage +test:test coverageReport

      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)
